# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'semapos' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for semapos

  

  platform :ios, '9.0'
  target 'semaposTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'semapos-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for semapos-tvOS

  target 'semapos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
